Document Pdf action (#526)
* Instructions to edit the manual

* Error catching in make_manual_pdf.sh script

* Fix checkout branch

diff --git a/.github/workflows/tex-upload.yml b/.github/workflows/tex-upload.yml
--- a/.github/workflows/tex-upload.yml
+++ b/.github/workflows/tex-upload.yml
@@ -9,12 +9,12 @@
 #
 # -----------------------------------------------------------------------------
 
-# Workflow to upload the PDF file of the AtChem2 manual before a Pull
-# Request is merged
+# Workflow to upload the PDF file of the AtChem2 user manual before
+# merging a Pull Request
 #
-# The PDF file is generated by the `AtChem2 PDF build' worflow, which
-# is automatically triggered when the LaTeX source files (.tex, .svg)
-# are modified
+# The file is generated by the `AtChem2 PDF build' worflow, which is
+# automatically triggered when the LaTeX source files (.tex, .svg) are
+# modified
 # -------------------------------------------------------------------- #
 
 name: AtChem2 PDF upload
@@ -24,22 +24,24 @@ name: AtChem2 PDF upload
 on:
 
   # Run manually from the Actions tab. Requires the name of the branch
-  # to update and the download URL of the PDF artifact (from workflow
-  # `AtChem2 PDF build`)
+  # to update and the download URL of the PDF artifact
   workflow_dispatch:
     inputs:
+      repo:
+        description: 'Name of repo'
+        required: true
       pr_branch:
-        description: 'Branch name'
+        description: 'Name of branch'
         required: true
       pdf_url:
-        description: 'Download URL'
+        description: 'PDF artifact URL'
         required: true
 
 # ------------------------------ JOBS ------------------------------ #
 
 # This workflow contains a single job called `upload_pdf_manual` which
-# uses git to commit the PDF file of the manual to the uploads it to
-# the repository jobs:
+# retrieves the PDF file of the manual and pushes it to the relevant
+# branch using git
 jobs:
 
   upload_pdf_manual:
@@ -60,25 +62,30 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.inputs.pr_branch }}
+          repository: ${{ github.event.inputs.repo }}
 
       # -------------------------------------------------------------
-      # Fetch PDF file of the manual
+      # Retrieve PDF artifact generated by workflow `AtChem2 PDF build`
       #
       # ACTION: https://github.com/marketplace/actions/upload-a-build-artifact
-      - name: Download PDF artifact
+      - name: Retrieve pdf artifact
         run: |
           curl -L ${{ github.event.inputs.pdf_url }} --output doc/AtChem2-Manual.pdf
+          if [ ! -f doc/AtChem2-Manual.pdf ]; then
+            echo "[!] PDF artifact not found"
+            exit 1
+          fi
 
       # -------------------------------------------------------------
-      # Commit and push
-      - name: Add pdf
+      # Push PDF file to branch
+      - name: Push pdf to branch
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           # configure git
           git config --local user.name "github-actions[bot]"
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
-          # push PDF file to branch
+          # commit and push pdf
           git add doc/AtChem2-Manual.pdf
           git commit -m "Update AtChem2-Manual.pdf" || echo "No changes to commit"
           git push
