Fix checkout branch

diff --git a/.github/workflows/tex-upload.yml b/.github/workflows/tex-upload.yml
--- a/.github/workflows/tex-upload.yml
+++ b/.github/workflows/tex-upload.yml
@@ -27,11 +27,14 @@ on:
   # to update and the download URL of the PDF artifact
   workflow_dispatch:
     inputs:
+      repo:
+        description: 'Name of repo'
+        required: true
       pr_branch:
-        description: 'Branch name'
+        description: 'Name of branch'
         required: true
       pdf_url:
-        description: 'Download URL'
+        description: 'PDF artifact URL'
         required: true
 
 # ------------------------------ JOBS ------------------------------ #
@@ -59,6 +62,7 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.inputs.pr_branch }}
+          repository: ${{ github.event.inputs.repo }}
 
       # -------------------------------------------------------------
       # Retrieve PDF artifact generated by workflow `AtChem2 PDF build`
@@ -67,6 +71,10 @@ jobs:
       - name: Retrieve pdf artifact
         run: |
           curl -L ${{ github.event.inputs.pdf_url }} --output doc/AtChem2-Manual.pdf
+          if [ ! -f doc/AtChem2-Manual.pdf ]; then
+            echo "[!] PDF artifact not found"
+            exit 1
+          fi
 
       # -------------------------------------------------------------
       # Push PDF file to branch
