Use download action

diff --git a/.github/workflows/tex-upload.yml b/.github/workflows/tex-upload.yml
--- a/.github/workflows/tex-upload.yml
+++ b/.github/workflows/tex-upload.yml
@@ -67,21 +67,29 @@ jobs:
       # -------------------------------------------------------------
       # Retrieve PDF artifact generated by workflow `AtChem2 PDF build`
       #
-      # ACTION: https://github.com/marketplace/actions/upload-a-build-artifact
+      # ACTION: https://github.com/marketplace/actions/download-workflow-artifact
       - name: Retrieve pdf artifact
+        uses: dawidd6/action-download-artifact@v9
+        with:
+          repo: ${{ github.event.inputs.repo }}
+          branch: ${{ github.event.inputs.pr_branch }}
+          workflow: tex-build.yml
+          name: AtChem2-Manual
+          path: doc
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Check pdf artifact
         run: |
-          curl -L ${{ github.event.inputs.pdf_url }} --output doc/AtChem2-Manual.pdf
-          if [ ! -f doc/AtChem2-Manual.pdf ]; then
-            echo "[!] Artifact not found"
-            exit 1
-          else
-            file_type="$(file -b --mime-type doc/AtChem2-Manual.pdf)"
-            if [ "$file_type" != "application/pdf" ]; then
-              echo "[!] Artifact not a pdf"
-              echo "$file_type"
+            if [ ! -f doc/AtChem2-Manual.pdf ]; then
+              echo "[!] Artifact not found"
               exit 1
+            else
+              file_type="$(file -b --mime-type doc/AtChem2-Manual.pdf)"
+              if [ "$file_type" != "application/pdf" ]; then
+                echo "[!] Artifact not a pdf ($file_type)"
+                exit 1
+              fi
             fi
-          fi
 
       # -------------------------------------------------------------
       # Push PDF file to branch
